name: Publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Install VSCE
        run: npm install -g vsce

      - name: Publish extension to VSCode Marketplace
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}

      - name: Install OVSX
        run: npm install -g ovsx

      - name: Publish extension to OpenVSX Marketplace
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OVSX_TOKEN }}
