name: Publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Set release tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Publish extension
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: npm run vsce:publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
